language: node_js
node_js:
    - 14
    - 16
    - 17

script:
    - npm run lint
    - npm run build
    - npm run init:examples
    - npm run build:examples:silent
    - npm run test
    - npm run test:int
    - npm run test:coverage:coveralls
