before_script:
   - export NODE_OPTIONS=–max_old_space_size=4096
dist: jammy
language: node_js
node_js:
    - 16
    - 18
    - 20
    - 21

script:
    - npm run lint
    - npm run build
    - npm run init:examples
    - npm run build:examples:silent
    - npm run test
    - npm run test:int
    # - npm run test:coverage:coveralls
